app:
  port: APP_PORT
  secret: APP_SECRET
  secure: APP_SECURE

database:
  host: DATABASE_HOST
  type: DATABASE_TYPE
  port: DATABASE_PORT
  database: DATABASE_NAME
  username: DATABASE_USERNAME
  password: DATABASE_PASSWORD
  dropSchema: DATABASE_DROP_SCHEMA

redis:
  host: REDIS_HOST
  port: REDIS_PORT
  username: REDIS_USERNAME
  password: REDIS_PASSWORD
