app:
  port: APP_PORT
  secret: APP_SECRET

database:
  host: DATABASE_HOST
  type: DATABASE_TYPE
  port: DATABASE_PORT
  database: DATABASE_NAME
  username: DATABASE_USERNAME
  password: DATABASE_PASSWORD

redis:
  host: REDIS_HOST
  port: REDIS_PORT
  username: REDIS_USERNAME
  password: REDIS_PASSWORD
