app:
  secret: GENERIC_APP_SECRET
  port: 3000

database:
  type: mysql
  host: localhost
  port: 3306
  database: squatch
  name: default
  entities:
    - dist/database/entities/*
  synchronize: true
  cache: true
  supportsJson: true
  dropSchema: false

redis:
  host: localhost
  port: 6379

pagination:
  results: 15
